version : '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
  php:
    # L'image est construite grâce au Dockerfile
    build: .
    volumes:
      - ./:/code
  mysql:
    image: mysql:8.2
    environment:
      # 🚨 Changer si vous utilisez cette configuration en production
      MYSQL_ROOT_PASSWORD: root # ⬅︎ 🚨 À changer si production
      MYSQL_DATABASE: appdb
      MYSQL_USER: user # ⬅︎ 🚨 À changer si production
      MYSQL_PASSWORD: password # ⬅︎ 🚨 À changer si production
    volumes:
      - data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root # ⬅︎ 🚨 À changer si production
    ports:
      - "8081:80"

volumes:
  data: